# Pre-commit hooks for Pact Rust development
# Install with: pip install pre-commit && pre-commit install

repos:
  # Rust formatting
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false

  # Rust linting
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

  # Check Cargo.toml formatting
  - repo: local
    hooks:
      - id: cargo-toml-fmt
        name: cargo-toml fmt
        entry: taplo fmt
        language: system
        files: Cargo\.toml$
        pass_filenames: true

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Security audit
  - repo: local
    hooks:
      - id: cargo-audit
        name: cargo audit
        entry: cargo audit
        language: system
        pass_filenames: false
        types: [rust]

  # Check for typos
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.26
    hooks:
      - id: typos

  # License header check (optional)
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        name: Add license header
        files: \.rs$
        args:
          - --license-filepath
          - .license-header.txt
          - --comment-style
          - //

# Configuration for specific hooks
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: 2.9.0