# Rust formatting configuration for Pact
# Using only stable features

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
