[package]
name = "pact-integration-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_integration" 
path = "test_integration.rs"

[dependencies]
pact-lexer = { path = "pact-lexer" }
pact-parser = { path = "pact-parser" }
pact-errors = { path = "pact-errors" }
pact-shared-types = { path = "pact-shared-types" }